### PR TITLE
fix bug in river simplification fixes #73

### LINKED ISSUE #73: Bug in simplification of river geometry.
This ain't right.
screen shot 2018-07-13 at 10 21 28 am

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
gif_frame_a_20170827_14
Also adjusted the download to pull down less data and changed the simplification tolerance to 1000m. I think this is looking pretty good.
This is what the rivers looked like before:
gif_frame_a_20170901_23

### CODE REVIEW

**Comment by jzwart** [comment]
I'm just noticing that Lake Pontchartrain has a flow line going through it and it looks kinda funny. Is this pulling flowline from NHD which goes through waterbodies?

File: 1_fetch/src/fetch_river_geometry.R [hunk 1]
```diff
@@ -1,38 +1,34 @@
...
-  # '</ogc:PropertyIsGreaterThan>',
-  # ...
-  # '</ogc:And>',
   filterXML <- paste0('<?xml version="1.0"?>',
                       '<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml" service="WFS" version="1.1.0" outputFormat="application/json" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd">',
                       '<wfs:Query xmlns:feature="http://gov.usgs.cida/nhdplus" typeName="feature:nhdflowline_network" srsName="EPSG:4326">',
                       '<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">',
+                      '<ogc:And>',
+                      '<ogc:PropertyIsGreaterThan>',
+                      '<ogc:PropertyName>streamorde</ogc:PropertyName>',
```
Comment (jzwart) [inline 1_fetch/src/fetch_river_geometry.R]: should `'<ogc:PropertyName>streamorde</ogc:PropertyName>'` be `'<ogc:PropertyName>streamorder</ogc:PropertyName>'` ? missing the last `r` in `streamorder`
